#!/usr/bin/env python3
"""
Quick setup script for enterprise features
Generates secure secrets and creates .env file
"""

import os
import secrets
import sys
from pathlib import Path


def generate_jwt_secret():
    """Generate a secure JWT secret"""
    return secrets.token_urlsafe(32)


def check_docker():
    """Check if Docker is available"""
    import subprocess
    try:
        subprocess.run(["docker", "--version"], capture_output=True, check=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def create_env_file():
    """Create .env file with secure defaults"""
    env_path = Path(".env")
    
    if env_path.exists():
        response = input(".env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Keeping existing .env file")
            return False
    
    print("\n🔧 Setting up environment variables...\n")
    
    # Get Anthropic API key
    anthropic_key = input("Enter your ANTHROPIC_API_KEY: ").strip()
    if not anthropic_key:
        print("❌ ANTHROPIC_API_KEY is required")
        sys.exit(1)
    
    # Generate JWT secret
    jwt_secret = generate_jwt_secret()
    print(f"✅ Generated secure JWT_SECRET_KEY")
    
    # Get optional frontend URL
    frontend_url = input("Frontend URL (default: http://localhost:8501): ").strip()
    if not frontend_url:
        frontend_url = "http://localhost:8501"
    
    # Write .env file
    env_content = f"""# AI Threat Modeling Tool - Enterprise Configuration
# Generated by setup.py

# ===== ANTHROPIC API =====
ANTHROPIC_API_KEY={anthropic_key}

# ===== DATABASE =====
DATABASE_URL=postgresql://postgres:postgres@postgres:5432/threat_modeling

# ===== REDIS =====
REDIS_URL=redis://redis:6379/0

# ===== SECURITY =====
JWT_SECRET_KEY={jwt_secret}

# ===== API CONFIGURATION =====
API_HOST=0.0.0.0
API_PORT=8000

# ===== STREAMLIT CONFIGURATION =====
STREAMLIT_SERVER_PORT=8501
STREAMLIT_SERVER_HEADLESS=true
STREAMLIT_BROWSER_GATHER_USAGE_STATS=false

# ===== FRONTEND =====
FRONTEND_URL={frontend_url}

# ===== RATE LIMITING =====
API_RATE_LIMIT_PER_MINUTE=100

# ===== LOGGING =====
LOG_LEVEL=INFO
"""
    
    env_path.write_text(env_content)
    print(f"✅ Created .env file\n")
    return True


def main():
    """Main setup flow"""
    print("=" * 60)
    print("🔒 AI Threat Modeling Tool - Enterprise Setup")
    print("=" * 60)
    print()
    
    # Check Docker
    if not check_docker():
        print("⚠️  Warning: Docker not found. Install Docker to use docker-compose.")
        print("   Visit: https://docs.docker.com/get-docker/")
        print()
    
    # Create .env file
    if not create_env_file():
        print("\n✅ Setup complete (using existing .env)")
        sys.exit(0)
    
    print("=" * 60)
    print("✅ Setup Complete!")
    print("=" * 60)
    print()
    print("Next steps:")
    print()
    print("1. Start services:")
    print("   docker compose up --build")
    print()
    print("2. Initialize database (in another terminal):")
    print("   docker compose exec api python init_db.py --all")
    print()
    print("3. Access the application:")
    print("   - Web UI: http://localhost:8501")
    print("   - API Docs: http://localhost:8000/api/docs")
    print("   - Default admin: admin@example.com / admin123")
    print()
    print("⚠️  IMPORTANT: Change the default admin password immediately!")
    print()
    print("For more information, see:")
    print("   - README_ENTERPRISE.md - Enterprise features overview")
    print("   - ENTERPRISE_FEATURES.md - Detailed feature guide")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
